services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    volumes:
      - .postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      AWS_REGION: ${AWS_REGION:-ca-central-1}
      AWS_ACEESS_KEY_ID: ${AWS_ACEESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      SERVICES: "lambda"
      FUNCTIONS_DIR: ${PWD}/functions
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-tush-dev}
      AWS_LAMBDA_FN_NAME: ${AWS_LAMBDA_FN_NAME:-tush-processor-dev}
      LAMBDA_REMOTE_DOCKER: false
    ports:
      - "4566:4566"
      - 4510-4559:4510-4559
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/setup.sh:/etc/localstack/init/ready.d/script.sh
  functions:
    container_name: functions
    build:
      dockerfile: Dockerfile
      context: ./functions
    volumes:
      - ./functions:/functions

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
