services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    volumes:
      - .postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      AWS_REGION: ${AWS_REGION:-ca-central-1}
      AWS_ACEESS_KEY_ID: ${AWS_ACEESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      SERVICES: "lambda"
      DEBUG: 1
      FUNCTIONS_DIR: ${PWD}/functions/dist
      BLOB_READ_WRITE_TOKEN: ${BLOB_READ_WRITE_TOKEN:-test}
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/setup.sh:/etc/localstack/init/ready.d/script.sh
  functions:
    container_name: functions
    build:
      dockerfile: Dockerfile
      context: ./functions
    volumes:
      - ./functions:/functions
      - /functions/node_modules

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
