services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-tush}
    volumes:
      - .postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      DEFAULT_REGION: ${AWS_REGION:-ca-central-1}
      AWS_ACEESS_KEY_ID: ${AWS_ACEESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      SERVICES: "s3"
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-tush-dev}
      DISABLE_CORS_CHECKS: 0
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/setup.sh:/etc/localstack/init/ready.d/script.sh

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
