name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: "no"

      - name: Deploy to AWS
        id: deploy-to-aws
        run: |
          cd functions
          npm ci || npm i
          npx esbuild index.ts --bundle --minify --sourcemap --platform=node --external:sharp --target=es2020 --outfile=dist/index.js
          cd dist
          npm init -y && npm install sharp --no-save --no-package-lock
          zip -jr ../deploy.zip .
          cd ..
          aws lambda update-function-code --function-name "convert-image-format" --zip-file=fileb://deploy.zip
